### ISSUE TITLE
kafka 1.0

### ISSUE THREAD

**Issue by harksin** [aerospike/aerospike-kafka-connector#3]
hi,

project is still active ?
what about kafka 1.0 and aerospike client 4.x ?

**Comment by jhecking** [comment]
Yes, it is still active! I will take a look at upgrading to Aerospike Client v4.1 and Kafka v1.0.

**Comment by jhecking** [comment]
I have released `aerospike-kafka-connector` v0.0.6 today. It should show up on the central Maven repository soon.
